[package]
name = "vm"
version = "0.1.0"
authors = ["Jim Connell <james.d.connell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_matches = "1.4.0"
